{% set name = "websocket-client" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/websocket-client-{{ version }}.tar.gz
  sha256: 79d730c9776f4f112f33b10b78c8d209f23b5806d9a783e296b3813fc5add2f1

build:
  number: 0
  noarch: python
  entry_points:
    - wsdump=websocket._wsdump:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - websocket
    - websocket.tests
  commands:
    - pip check
    - wsdump --help
  requires:
    - pip

about:
  home: https://github.com/websocket-client/websocket-client.git
  summary: WebSocket client for Python with low level API options
  dev_url: https://github.com/websocket-client/websocket-client/
  doc_url: https://websocket-client.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scopatz
    - BastianZim
    - wshanks
