{% set name = "websocket-client" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/websocket-client-{{ version }}.tar.gz
  sha256: 21861f8645eb5725d1becfe86d7e7ae1a31d98b72556f9d44fcc5100976353cf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # Cannot be no-arch due to bytecode issues.

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - websocket
    - websocket.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/websocket-client/websocket-client.git
  summary: WebSocket client for Python with low level API options
  dev_url: https://github.com/websocket-client/websocket-client/
  doc_url: https://websocket-client.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
    - BastianZim
    - wshanks
