{% set name = "websocket-client" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/websocket-client-{{ version }}.tar.gz
  sha256: 21861f8645eb5725d1becfe86d7e7ae1a31d98b72556f9d44fcc5100976353cf

build:
  number: 0
  noarch: python
  entry_points:
    - wsdump=websocket._wsdump:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - websocket
    - websocket.tests
  commands:
    - pip check
    - wsdump --help
  requires:
    - pip

about:
  home: https://github.com/websocket-client/websocket-client.git
  summary: WebSocket client for Python with low level API options
  dev_url: https://github.com/websocket-client/websocket-client/
  doc_url: https://websocket-client.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
    - BastianZim
    - wshanks
