{% set name = "websocket-client" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/websocket-client-{{ version }}.tar.gz
  sha256: b68e4959d704768fa20e35c9d508c8dc2bbc041fd8d267c0d7345cffe2824568

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - websocket
    - websocket.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/websocket-client/websocket-client/
  summary: WebSocket client for Python with low level API options
  dev_url: https://github.com/websocket-client/websocket-client/
  doc_url: https://websocket-client.readthedocs.io/en/latest/
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - scopatz
